# Config build
language: python
matrix:
  include:
    - python: 3.7.2
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt
# Enabling the quiet flag can be useful if you’re trying to avoid log file size limit
git:
  quiet: true
# command to run scripts
script:
  - python -m unittest discover
  - pylint mlfinlab --rcfile=.pylintrc -f text
  - coverage